# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yaml_waml}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["KAKUTANI Shintaro", "Akira Ikeda"]
  s.date = %q{2009-10-20}
  s.description = %q{Plugin gem to workaround for fixing output result of 'to_yaml' method treats multibyte UTF-8 string(such as japanese) as binary. }
  s.email = %q{shintaro@kakutani.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "benchmark/huge_yaml_dump.rb",
     "init.rb",
     "install.rb",
     "lib/yaml_waml.rb",
     "spec/spec_helper.rb",
     "spec/to_yaml_spec.rb",
     "tasks/yaml_waml_tasks.rake",
     "yaml_waml.gemspec"
  ]
  s.homepage = %q{http://github.com/kakutani/yaml_waml}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{'to_yaml' workaround for multibyte UTF-8 string.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/to_yaml_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

